{"uuid": "645f4f55-6213-4d23-9350-d511658a69fe", "children": ["d1b9fadc-7592-48e3-b6f0-9590e952ff00"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available\n\n", "trace": "  File \"C:\\Users\\asya4\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\PycharmProjects\\qa_guru_8_12\\tests\\conftest.py\", line 21, in setup_browser\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698508609408, "stop": 1698508610013}], "start": 1698508609408, "stop": 1698508610149}